### ISSUE TITLE
Fails to run with proxy=true

### ISSUE THREAD

**Issue by mlorentz** [mtdoyle/CLSpeedPhantomJS#1]
I set "proxy=true" in clspeed/local.properties and now the output is constant errors. I noticed proxy settings in CLSpeed.java but they must not be working correctly.

```
        if (properties.getProperty("proxy").equalsIgnoreCase("true")) {
            caps.setCapability("proxy", "localhost:3128");
            caps.setCapability("proxy-type", "http");
```

Example of the errors:

```
[ERROR - 2016-05-19T02:57:12.668Z] RouterReqHand - _handle.error - {"stack":"_getProxySettingsFromCapabilities@phantomjs://code/session.js:131:41\nSession@phantomjs://code/session.js:165:62\n_postNewSessionCommand@phantomjs://code/session_manager_request_handler.js:75:49\n_handle@phantomjs://code/session_manager_request_handler.js:44:35\n_handle@phantomjs://code/router_request_handler.js:70:37","line":131,"sourceURL":"phantomjs://code/session.js"}

  phantomjs://platform/console++.js:263 in error
[ERROR - 2016-05-19T02:57:12.672Z] RouterReqHand - _handle.error - {"stack":"_getProxySettingsFromCapabilities@phantomjs://code/session.js:131:41\nSession@phantomjs://code/session.js:165:62\n_postNewSessionCommand@phantomjs://code/session_manager_request_handler.js:75:49\n_handle@phantomjs://code/session_manager_request_handler.js:44:35\n_handle@phantomjs://code/router_request_handler.js:70:37","line":131,"sourceURL":"phantomjs://code/session.js"}

  phantomjs://platform/console++.js:263 in error
[ERROR - 2016-05-19T02:57:12.673Z] RouterReqHand - _handle.error - {"stack":"_getProxySettingsFromCapabilities@phantomjs://code/session.js:131:41\nSession@phantomjs://code/session.js:165:62\n_postNewSessionCommand@phantomjs://code/session_manager_request_handler.js:75:49\n_handle@phantomjs://code/session_manager_request_handler.js:44:35\n_handle@phantomjs://code/router_request_handler.js:70:37","line":131,"sourceURL":"phantomjs://code/session.js"}

  phantomjs://platform/console++.js:263 in error
```

**Comment by mtdoyle** [comment]
I believe the current code in the repository is broken. I think I'll revert the proxy code since I couldn't get it to work locally and having phantomjs configured properly to not load images will make the proxy unnecessary.

**Comment by mlorentz** [comment]
Disabling image loading would be an improvement. However, I think the proxy will still be useful for javascript files.

**Comment by mtdoyle** [comment]
Proxy works now

**Comment by mlorentz** [comment]
Yea, it is looking a lot better after the updates today. I tried out the new code. From the squid log it looks like images are turned off and a decent amount of http requests are being served from the squid cache. Everything was humming along nicely until I started getting "Bad address" for every address. CenturyLink's site must be down for maintenance. When I try my own address it shows 12mbit max while I normally see 1Gbit.

**Comment by mlorentz** [comment]
The cache is definitely doing its job. I ran a [squid log file analyzer](http://squidanalyzer.darold.net/) and got the following stats: 

Requests:
cache-hit: 198,550
cache-miss: 191,061

Bytes:
cache-hit: 1,563,825,851
cache-miss: 1,934,514,847

**Comment by mtdoyle** [comment]
I had the same string of "bad addresses" yesterday. Of the ~10K addresses, only ~3K succeeded. I believe I normally get about 7-8K successful checks.
