### ISSUE TITLE
Images are being loaded

### ISSUE THREAD

**Issue by mlorentz** [mtdoyle/CLSpeedPhantomJS#2]
The output shows images being loaded ("loadImages":true) even though CLSpeed.java attempts to disable them. Even if the HTTP proxy is successfully enabled, I think disabling images will reduce the overheard of PhantomJS constantly grabbing images from the proxy.

CLSpeed.java:
`caps.setCapability("loadImages", false);`

Sample output:
`[INFO  - 2016-05-19T03:43:30.044Z] Session [da2fd070-1d73-11e6-b53a-5b65a7ccfd06] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":true}
`

**Comment by mtdoyle** [comment]
Good eye, I actually did catch this but must not have pushed my latest code: https://www.dslreports.com/forum/r30756713-
